[theme]
primaryColor = "#0A21C0"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "Inter"

[server]
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false

